# Generated by Django 5.0.1 on 2024-09-26 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_purchasedcourse'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='category',
            field=models.CharField(choices=[('web', 'Web Development'), ('data', 'Data Science'), ('cyber', 'Cyber Security')], default='web', max_length=20),
        ),
        migrations.AlterField(
            model_name='course',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
